name: Pull Request
on:
  pull_request:
    paths-ignore:
      - '**.md'
    branches:
      - main

jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x
      
      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with: 
          name: coverage
          path: coverage/lcov.info

  sonar:
    name: Sonar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  
